describe('Comprando uma Passagem no RY', () => {
  it('Compra RY1', () => {
    cy.viewport(1000, 880)
    //visitar a Página
    cy.visit('https://www.ryanair.com/pt/pt')
    cy.wait(1500)
    cy.xpath('/html/body/div/div/div[3]/button[3]').click()
    cy.wait(1500)
    cy.xpath('/html/body/hp-app-root/hp-home-container/hp-home/hp-search-widget-container/hp-search-widget/div/hp-flight-search-widget-container/fsw-flight-search-widget-container/fsw-flight-search-widget/div/fsw-flight-search-widget-controls-container/fsw-flight-search-widget-content-container/fsw-flight-search-widget-content/div[1]/div/div/fsw-input-button/div/div[2]/input').click()
    cy.wait(1500)
    cy.xpath('/html/body/ry-tooltip/div[2]/hp-app-controls-tooltips/fsw-controls-tooltips-container/fsw-controls-tooltips/fsw-destination-container/fsw-airports/fsw-countries/div[5]/div[1]/span').click()
    cy.wait(1500)
    cy.xpath('/html/body/ry-tooltip/div[2]/hp-app-controls-tooltips/fsw-controls-tooltips-container/fsw-controls-tooltips/fsw-destination-container/fsw-airports/div/fsw-airports-list/div[2]/div[1]/fsw-airport-item[7]/span/span').click()
    cy.wait(2000)
    cy.xpath('/html/body/ry-tooltip/div[2]/hp-app-controls-tooltips/fsw-controls-tooltips-container/fsw-controls-tooltips/fsw-flexible-datepicker-container/fsw-datepicker/ry-datepicker-desktop/month-toggle/div/div[2]/div/div[10]/div[2]').click()
    cy.wait(2000)
    cy.xpath('/html/body/ry-tooltip/div[2]/hp-app-controls-tooltips/fsw-controls-tooltips-container/fsw-controls-tooltips/fsw-flexible-datepicker-container/fsw-datepicker/ry-datepicker-desktop/month-toggle/div/div[2]/div/div[10]/div[2]').click()
    cy.wait(2000)
    cy.xpath('/html/body/ry-tooltip/div[2]/hp-app-controls-tooltips/fsw-controls-tooltips-container/fsw-controls-tooltips/fsw-flexible-datepicker-container/fsw-datepicker/ry-datepicker-desktop/div/calendar[1]/calendar-body/div[6]/div[13]/div').click()
    cy.wait(2000)
    cy.xpath('/html/body/ry-tooltip/div[2]/hp-app-controls-tooltips/fsw-controls-tooltips-container/fsw-controls-tooltips/fsw-flexible-datepicker-container/fsw-datepicker/ry-datepicker-desktop/div/calendar[2]/calendar-body/div[3]/div[4]/div').click()
    cy.wait(4000)
    cy.xpath('/html/body/hp-app-root/hp-home-container/hp-home/hp-search-widget-container/hp-search-widget/div/hp-flight-search-widget-container/fsw-flight-search-widget-container/fsw-flight-search-widget/div/fsw-flight-search-widget-controls-container/fsw-flight-search-widget-content-container/fsw-flight-search-widget-content/div[2]/div[2]/button').click()
    cy.wait(4000)
    cy.xpath('/html/body/app-root/flights-root/div/div/div/div/flights-lazy-content/flights-summary-container/flights-summary/div/div[1]/journey-container/journey/flight-list/ry-spinner/div/flight-card-new[1]/div/div/div[4]/flight-card-summary/div[2]/button').click()
    cy.wait(4000)
    cy.xpath('/html/body/app-root/flights-root/div/div/div/div/flights-lazy-content/flights-summary-container/flights-summary/div/div[2]/journey-container/journey/flight-list/ry-spinner/div/flight-card-new[1]/div/div/div[4]/flight-card-summary/div[2]/button').click()
    cy.wait(2500)
    cy.xpath('/html/body/app-root/flights-root/div/div/div/div/flights-lazy-content/fare-selector-container/fare-selector/div/fare-table-new-layout-container/fare-table-new-layout/table/thead/tr[2]/th[2]/div').click()
    cy.wait(2000)
    cy.xpath('/html/body/app-root/ry-portal/div/fare-table-upgrade-container/fare-table-upgrade/ry-dialog/div[2]/table/tfoot/tr/td[2]/fare-table-upgrade-footer/button').click()
    cy.wait(2000)
    cy.xpath('/html/body/app-root/flights-root/div/div/div/div/flights-lazy-content/flights-passengers/ry-spinner/pax-app-container/pax-app/ry-spinner/ry-login-touchpoint-container/ry-login-touchpoint/div/button/div/span').click()
    cy.wait(2000)
    cy.xpath('/html/body/app-root/flights-root/div/div/div/div/flights-lazy-content/flights-passengers/ry-spinner/pax-app-container/pax-app/ry-spinner/div/div/div[2]/pax-app-form-container/pax-app-form/form/pax-passenger-container/pax-passenger/div/pax-passenger-details-container/pax-passenger-details/pax-passenger-details-form-container/pax-details-form/ry-dropdown/div[2]/button').click()
    cy.xpath('/html/body/app-root/flights-root/div/div/div/div/flights-lazy-content/flights-passengers/ry-spinner/pax-app-container/pax-app/ry-spinner/div/div/div[2]/pax-app-form-container/pax-app-form/form/pax-passenger-container/pax-passenger/div/pax-passenger-details-container/pax-passenger-details/pax-passenger-details-form-container/pax-details-form/ry-dropdown/div[2]/div/div/ry-dropdown-item[1]/button').click()
    cy.xpath('/html/body/app-root/flights-root/div/div/div/div/flights-lazy-content/flights-passengers/ry-spinner/pax-app-container/pax-app/ry-spinner/div/div/div[2]/pax-app-form-container/pax-app-form/form/pax-passenger-container/pax-passenger/div/pax-passenger-details-container/pax-passenger-details/pax-passenger-details-form-container/pax-details-form/ry-input-d[1]/div/input').type('Hudson Silva')
    cy.xpath('/html/body/app-root/flights-root/div/div/div/div/flights-lazy-content/flights-passengers/ry-spinner/pax-app-container/pax-app/ry-spinner/div/div/div[2]/pax-app-form-container/pax-app-form/form/pax-passenger-container/pax-passenger/div/pax-passenger-details-container/pax-passenger-details/pax-passenger-details-form-container/pax-details-form/ry-input-d[2]/div/input').type('Black')
    cy.xpath('/html/body/app-root/flights-root/div/div/div/div/flights-lazy-content/ng-component/div/continue-flow-container/continue-flow/div/div/span/button').click()
    cy.wait(9000)
    cy.xpath('/html/body/bags-root/bags-booking-container/div/main/div/section[1]/div/bags-cabin-lazy-bag/bags-cabin-bag-section/bags-bag-layout/div/div[3]/div[2]/bags-pax-table-journey-container/div/div[2]/bags-cabin-bag-table-controls-container/bags-cabin-bag-table-controls/div[1]/bags-small-bag-pax-control/div/bags-product-selector/div/div/div[1]/ry-radio-circle-button/label').click()
    cy.wait(3000)
    cy.xpath('/html/body/bags-root/bags-booking-container/div/main/div/section[4]/bags-continue-flow-container/bags-continue-flow/button').click()
    cy.wait(4000)
    cy.xpath('/html/body/seats-root/div/div/div[2]/ng-component/seats-container-v2/main/div[2]/div/div/div[2]/div[1]/div[2]/div[3]/div/passenger-carousel/div[2]/button').click()
    cy.wait(5000)
    cy.xpath('/html/body/seats-root/div/div/div[2]/ng-component/seats-container-v2/main/div[2]/div/div/div[2]/div[1]/div[2]/div[3]/div/passenger-carousel/div[2]/button').click()
    cy.wait(5000)
    cy.get('.enhanced-takeover-beta__product-dismiss-cta').click()
    cy.wait(5000)
    cy.xpath('/html/body/app-root/ng-component/div/div/div/main/div/airport-and-flight-container/button').click()
    cy.get('.transport__cta').click()
    cy.wait(4000)
    cy.get('.auth-popup__header-title').should('be.visible')
    .and('exist')
    




  })
})